import PptxGenJS from "pptxgenjs";
import fs from "node:fs";
import path from "node:path";

/* =========================================================
   TYPES
   ========================================================= */

export interface DeckItem {
  name: string;
  quantity: number;
  revenuePaise: number;
}

export interface DeckStockItem {
  name: string;
  quantity: number;
  reorderLevel: number;
  unit: string;
}

export interface AnalysisDeckInput {
  outputPath: string;
  shopName: string;
  from: string;
  to: string;

  totalBills: number;
  totalSalesPaise: number;
  totalTaxPaise: number;
  totalProfitPaise: number;

  paymentBreakdown: {
    mode: string;
    amountPaise: number;
  }[];

  topItems: DeckItem[];
  lowStockItems: DeckStockItem[];
}

/* =========================================================
   HELPERS
   ========================================================= */

function rupees(paise: number): string {
  return `₹${(paise / 100).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function safeNumber(value: unknown): number {
  const n = Number(value);
  return Number.isFinite(n) ? n : 0;
}

/* =========================================================
   GENERATE ANALYSIS DECK
   ========================================================= */

export async function generateAnalysisDeck(
  input: AnalysisDeckInput
): Promise<string> {
  const outputDir = path.dirname(
    input.outputPath
  );

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, {
      recursive: true,
    });
  }

  /*
   * PptxGenJS typing differs between package versions.
   * Casting the imported constructor to any keeps the code
   * compatible with the current package typings.
   */
  const Pptx = PptxGenJS as any;
  const pptx = new Pptx();

  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "Nebula Kirana";
  pptx.company = "Nebula KnowLab";
  pptx.subject =
    "Supermarket Operations Analysis";
  pptx.title =
    `${input.shopName} - Sales Analysis`;
  pptx.lang = "en-IN";

  pptx.theme = {
    headFontFace: "Aptos Display",
    bodyFontFace: "Aptos",
    lang: "en-IN",
  };

  /* =======================================================
     SLIDE 1 - TITLE
     ======================================================= */

  {
    const slide = pptx.addSlide();

    slide.background = {
      color: "F8FAFC",
    };

    slide.addText(
      input.shopName,
      {
        x: 0.7,
        y: 1.45,
        w: 11.5,
        h: 0.7,
        fontSize: 30,
        bold: true,
        align: "center",
        color: "0F172A",
      }
    );

    slide.addText(
      "Supermarket Operations Analysis",
      {
        x: 0.7,
        y: 2.2,
        w: 11.5,
        h: 0.5,
        fontSize: 22,
        align: "center",
        color: "334155",
      }
    );

    slide.addText(
      `${input.from} → ${input.to}`,
      {
        x: 0.7,
        y: 2.9,
        w: 11.5,
        h: 0.4,
        fontSize: 15,
        align: "center",
        color: "64748B",
      }
    );

    slide.addText(
      "Generated by Nebula Kirana Agent",
      {
        x: 0.7,
        y: 6.7,
        w: 11.5,
        h: 0.3,
        fontSize: 10,
        align: "center",
        color: "94A3B8",
      }
    );
  }

  /* =======================================================
     SLIDE 2 - EXECUTIVE SUMMARY
     ======================================================= */

  {
    const slide = pptx.addSlide();

    slide.addText(
      "Executive Summary",
      {
        x: 0.6,
        y: 0.35,
        w: 12,
        h: 0.5,
        fontSize: 25,
        bold: true,
        color: "0F172A",
      }
    );

    const cards = [
      {
        title: "Total Sales",
        value: rupees(
          input.totalSalesPaise
        ),
      },
      {
        title: "Bills",
        value: String(
          input.totalBills
        ),
      },
      {
        title: "Tax Collected",
        value: rupees(
          input.totalTaxPaise
        ),
      },
      {
        title: "Estimated Profit",
        value: rupees(
          input.totalProfitPaise
        ),
      },
    ];

    cards.forEach(
      (card, index) => {
        const x =
          0.65 + index * 3.05;

        slide.addText(
          card.title,
          {
            x,
            y: 1.35,
            w: 2.65,
            h: 0.35,
            fontSize: 12,
            bold: true,
            color: "64748B",
            align: "center",
          }
        );

        slide.addText(
          card.value,
          {
            x,
            y: 1.75,
            w: 2.65,
            h: 0.65,
            fontSize: 23,
            bold: true,
            color: "0F172A",
            align: "center",
          }
        );
      }
    );

    slide.addText(
      "Key observations",
      {
        x: 0.8,
        y: 3.05,
        w: 3,
        h: 0.4,
        fontSize: 17,
        bold: true,
        color: "0F172A",
      }
    );

    const observations: string[] = [];

    if (
      input.totalSalesPaise > 0
    ) {
      observations.push(
        `Sales generated during the selected period: ${rupees(
          input.totalSalesPaise
        )}.`
      );
    }

    if (
      input.totalBills > 0
    ) {
      observations.push(
        `The shop processed ${input.totalBills} completed bill${
          input.totalBills === 1
            ? ""
            : "s"
        }.`
      );
    }

    if (
      input.lowStockItems.length > 0
    ) {
      observations.push(
        `${input.lowStockItems.length} product${
          input.lowStockItems.length ===
          1
            ? ""
            : "s"
        } require stock attention.`
      );
    } else {
      observations.push(
        "No products are currently below their reorder level."
      );
    }

    if (
      input.paymentBreakdown.length >
      0
    ) {
      const highestPayment =
        [...input.paymentBreakdown].sort(
          (a, b) =>
            b.amountPaise -
            a.amountPaise
        )[0];

      observations.push(
        `${highestPayment.mode} is the highest-value payment mode in the selected period.`
      );
    }

    slide.addText(
      observations.map(
        (item) => ({
          text: item,
          options: {
            bullet: {
              indent: 14,
            },
            hanging: 4,
          },
        })
      ),
      {
        x: 0.9,
        y: 3.55,
        w: 10.8,
        h: 2.1,
        fontSize: 15,
        breakLine: true,
        color: "334155",
        valign: "top",
      }
    );
  }

  /* =======================================================
     SLIDE 3 - PAYMENT ANALYSIS
     ======================================================= */

  {
    const slide = pptx.addSlide();

    slide.addText(
      "Payment Analysis",
      {
        x: 0.6,
        y: 0.35,
        w: 12,
        h: 0.5,
        fontSize: 25,
        bold: true,
        color: "0F172A",
      }
    );

    if (
      input.paymentBreakdown.length ===
      0
    ) {
      slide.addText(
        "No payment data available for this period.",
        {
          x: 1,
          y: 2.5,
          w: 10,
          h: 0.5,
          fontSize: 18,
          align: "center",
          color: "64748B",
        }
      );
    } else {
      const rows = [
        [
          {
            text: "Payment Mode",
            options: {
              bold: true,
            },
          },
          {
            text: "Amount",
            options: {
              bold: true,
            },
          },
        ],
        ...input.paymentBreakdown.map(
          (item) => [
            item.mode,
            rupees(
              item.amountPaise
            ),
          ]
        ),
      ];

      slide.addTable(
        rows as any,
        {
          x: 1.3,
          y: 1.35,
          w: 10,
          border: {
            type: "solid",
            color: "CBD5E1",
            pt: 1,
          },
          fontSize: 15,
          color: "334155",
          margin: 0.12,
          valign: "mid",
          rowH: 0.55,
        }
      );

      const totalPayments =
        input.paymentBreakdown.reduce(
          (sum, item) =>
            sum +
            safeNumber(
              item.amountPaise
            ),
          0
        );

      slide.addText(
        `Total: ${rupees(
          totalPayments
        )}`,
        {
          x: 1.3,
          y: 4.8,
          w: 10,
          h: 0.5,
          fontSize: 19,
          bold: true,
          align: "right",
          color: "0F172A",
        }
      );
    }
  }

  /* =======================================================
     SLIDE 4 - TOP SELLING ITEMS
     ======================================================= */

  {
    const slide = pptx.addSlide();

    slide.addText(
      "Top Selling Items",
      {
        x: 0.6,
        y: 0.35,
        w: 12,
        h: 0.5,
        fontSize: 25,
        bold: true,
        color: "0F172A",
      }
    );

    if (
      input.topItems.length === 0
    ) {
      slide.addText(
        "No sales item data available.",
        {
          x: 1,
          y: 2.5,
          w: 10,
          h: 0.5,
          fontSize: 18,
          align: "center",
          color: "64748B",
        }
      );
    } else {
      const items =
        input.topItems.slice(
          0,
          8
        );

      const rows = [
        [
          {
            text: "#",
            options: {
              bold: true,
            },
          },
          {
            text: "Product",
            options: {
              bold: true,
            },
          },
          {
            text: "Quantity",
            options: {
              bold: true,
            },
          },
          {
            text: "Revenue",
            options: {
              bold: true,
            },
          },
        ],

        ...items.map(
          (
            item,
            index
          ) => [
            String(index + 1),
            item.name,
            String(
              item.quantity
            ),
            rupees(
              item.revenuePaise
            ),
          ]
        ),
      ];

      slide.addTable(
        rows as any,
        {
          x: 0.8,
          y: 1.2,
          w: 11.4,
          border: {
            type: "solid",
            color: "CBD5E1",
            pt: 1,
          },
          fontSize: 13,
          color: "334155",
          margin: 0.1,
          valign: "mid",
          rowH: 0.5,
          colW: [
            0.6,
            5.1,
            2.0,
            3.7,
          ],
        }
      );
    }
  }

  /* =======================================================
     SLIDE 5 - INVENTORY HEALTH
     ======================================================= */

  {
    const slide = pptx.addSlide();

    slide.addText(
      "Inventory Health",
      {
        x: 0.6,
        y: 0.35,
        w: 12,
        h: 0.5,
        fontSize: 25,
        bold: true,
        color: "0F172A",
      }
    );

    if (
      input.lowStockItems.length ===
      0
    ) {
      slide.addText(
        "Inventory is currently above reorder levels.",
        {
          x: 1,
          y: 2.5,
          w: 10,
          h: 0.6,
          fontSize: 21,
          align: "center",
          color: "334155",
        }
      );
    } else {
      const items =
        input.lowStockItems.slice(
          0,
          12
        );

      const rows = [
        [
          {
            text: "Product",
            options: {
              bold: true,
            },
          },
          {
            text: "Current Stock",
            options: {
              bold: true,
            },
          },
          {
            text: "Reorder Level",
            options: {
              bold: true,
            },
          },
          {
            text: "Unit",
            options: {
              bold: true,
            },
          },
        ],

        ...items.map(
          (item) => [
            item.name,
            String(
              item.quantity
            ),
            String(
              item.reorderLevel
            ),
            item.unit,
          ]
        ),
      ];

      slide.addTable(
        rows as any,
        {
          x: 0.8,
          y: 1.15,
          w: 11.4,
          border: {
            type: "solid",
            color: "CBD5E1",
            pt: 1,
          },
          fontSize: 12,
          color: "334155",
          margin: 0.1,
          valign: "mid",
          rowH: 0.48,
          colW: [
            5.0,
            2.1,
            2.1,
            2.2,
          ],
        }
      );

      slide.addText(
        "Recommendation: review these products before the next replenishment cycle.",
        {
          x: 0.9,
          y: 6.1,
          w: 10.8,
          h: 0.45,
          fontSize: 13,
          italic: true,
          color: "64748B",
          align: "center",
        }
      );
    }
  }

  /* =======================================================
     SLIDE 6 - RECOMMENDATIONS
     ======================================================= */

  {
    const slide = pptx.addSlide();

    slide.addText(
      "Recommended Actions",
      {
        x: 0.6,
        y: 0.35,
        w: 12,
        h: 0.5,
        fontSize: 25,
        bold: true,
        color: "0F172A",
      }
    );

    const recommendations: string[] =
      [];

    if (
      input.lowStockItems.length >
      0
    ) {
      recommendations.push(
        `Prioritize replenishment for ${input.lowStockItems
          .slice(0, 5)
          .map(
            (x) => x.name
          )
          .join(", ")}.`
      );
    }

    if (
      input.topItems.length > 0
    ) {
      recommendations.push(
        `Maintain availability of top-selling products such as ${input.topItems
          .slice(0, 3)
          .map(
            (x) => x.name
          )
          .join(", ")}.`
      );
    }

    if (
      input.paymentBreakdown.length >
      0
    ) {
      const highestPayment =
        [
          ...input.paymentBreakdown,
        ].sort(
          (a, b) =>
            b.amountPaise -
            a.amountPaise
        )[0];

      recommendations.push(
        `Keep ${highestPayment.mode} payment handling ready during peak billing periods.`
      );
    }

    if (
      input.totalProfitPaise > 0
    ) {
      recommendations.push(
        `Continue monitoring product-level margins to protect the estimated profit of ${rupees(
          input.totalProfitPaise
        )}.`
      );
    }

    if (
      recommendations.length === 0
    ) {
      recommendations.push(
        "Collect more sales and inventory activity to generate stronger operational recommendations."
      );
    }

    slide.addText(
      recommendations.map(
        (item) => ({
          text: item,
          options: {
            bullet: {
              indent: 16,
            },
            hanging: 5,
          },
        })
      ),
      {
        x: 1,
        y: 1.5,
        w: 10.5,
        h: 3.8,
        fontSize: 17,
        breakLine: true,
        color: "334155",
        valign: "top",
      }
    );

    slide.addText(
      "Nebula Kirana • Operations Agent",
      {
        x: 0.7,
        y: 6.8,
        w: 11.5,
        h: 0.25,
        fontSize: 9,
        align: "center",
        color: "94A3B8",
      }
    );
  }

  /* =======================================================
     WRITE PPTX
     ======================================================= */

  await pptx.writeFile({
    fileName: input.outputPath,
  });

  return input.outputPath;
}